src/java/manageBean/DonerCategoryBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manageBean;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import entity.DonorCategoryFacade;
import entity.DonorCategoryEntity;
import java.util.List;
import javax.annotation.PostConstruct;

/**
 *
 * @author user
 */
@Named(value = "donerCategoryBean")
@SessionScoped
public class DonerCategoryBean implements Serializable {

    /**
     * Creates a new instance of DonerCategoryBean.
     */
    @EJB
    private DonorCategoryFacade donorCategoryFacade;
    private DonorCategoryEntity currentDonorCategory;

    /* Don't need the setter and getter for DonorCategoryFacade because it is 
    * injected by the container.
     */
    public DonorCategoryEntity getCurrentDonorCategory() {
        return currentDonorCategory;
    }

    public List<DonorCategoryEntity> getAllCategories() {
        return donorCategoryFacade.findAll();
    }

    public DonerCategoryBean() {
    }

    @PostConstruct
    private void init() {
        donorCategoryFacade.populateContent();
    }
}

src/java/manageBean/DonorDataBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manageBean;

import entity.DonorEntity;
import entity.DonorFacade;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import org.primefaces.context.RequestContext;

/**
 *
 * @author user
 */
@Named(value = "donorDataBean")
@SessionScoped
public class DonorDataBean implements Serializable {

    final static public String DONOR_ADD_PAGE = "donerData-add";
    final static public String DONER_DATA_PAGE = "donerData";
    final static public String DONOR_VIEWDETAIL_PAGE = "donerData-detail";

    enum FormMode {
        CREATE, EDIT
    }
    @EJB
    private DonorFacade donerDataFacade;
    private DonorEntity currentDonerData;
    private FormMode formMode;

    public FormMode getFormMode() {
        return formMode;
    }

    public void setFormMode(FormMode formMode) {
        this.formMode = formMode;
    }

    public static Date getCurrentDate() {
        Calendar cal = Calendar.getInstance();
        return cal.getTime();
    }

    public DonorFacade getDonerDataFacade() {
        return donerDataFacade;
    }

    public void setDonerDataFacade(DonorFacade donerDataFacade) {
        this.donerDataFacade = donerDataFacade;
    }

    public DonorEntity getCurrentDonerData() {
        return currentDonerData;
    }

    public void setCurrentDonerData(DonorEntity currentDonerData) {
        this.currentDonerData = currentDonerData;
    }

    public List<DonorEntity> getAllDonerData() {
        return donerDataFacade.findAll();
    }

    /**
     * @deprecated Use {@link #getCurrentDate() } to get the current date.
     * @return
     */
    public Date prepareCreateDate() {

        Calendar cal = Calendar.getInstance();
        return cal.getTime();
    }

    public String saveDoner() {
        if (formMode == FormMode.CREATE) {
            donerDataFacade.create(currentDonerData);
        } else {
            currentDonerData.setCreate_date(getCurrentDate());
            donerDataFacade.edit(currentDonerData);
        }
        return DONER_DATA_PAGE;
    }

    public String prepareCreate() {
        currentDonerData = new DonorEntity();
        currentDonerData.setCreate_date(getCurrentDate());
        formMode = FormMode.CREATE;
        return DONOR_ADD_PAGE;
    }

    public String prepareEdit(DonorEntity donor) {
        currentDonerData = donor;
        formMode = FormMode.EDIT;
        return DONOR_ADD_PAGE;
    }

    public void removeDonerData() {
        donerDataFacade.remove(currentDonerData);
    }

    public void removeDonerDataAction(DonorEntity donorEntity) {
        currentDonerData = donorEntity;
        RequestContext requestContext = RequestContext.getCurrentInstance();
        requestContext.execute("PF('deleteDialogVar').show();");
    }

    public String viewDonerDataAction(DonorEntity donorEntity) {
        currentDonerData = donorEntity;
        return DONOR_VIEWDETAIL_PAGE;
    }
}

src/java/manageBean/ReceiverBean.java
package manageBean;

import entity.ReceiverFacade;
import entity.Receiver;
import entity.receiverDAO;
import javax.inject.Named;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.context.RequestContext;

/**
 * 票卷接受者
 *
 * @author hychen39@gmail.com
 */
@Named(value = "receiver")
@SessionScoped
public class ReceiverBean implements Serializable {

    static public final String FILENAME = "Receivers.txt";
    final static public String RECEIVER_ADD_PAGE = "individual-add";
    final static public String RECEIVER_DATA_PAGE = "individual";
    final static public String RECEIVER_VIEWDETAIL_PAGE = "individual-detail";

    enum FormMode {
        CREATE, EDIT
    }

    private int birthYear;
    private int birthMonth;
    private int birthDay;
    private receiverDAO receiverDAO;
    private List<Receiver> filteredReceiver;

    @EJB
    private ReceiverFacade receiverDataFacade;
    private Receiver currentReceiver;
    private FormMode formMode;

    public ReceiverFacade getReceiverDataFacade() {
        return receiverDataFacade;
    }

    public void setReceiverDataFacade(ReceiverFacade receiverDataFacade) {
        this.receiverDataFacade = receiverDataFacade;
    }

    public Receiver getCurrentReceiver() {
        return currentReceiver;
    }

    public void setCurrentReceiver(Receiver currentReceiver) {
        this.currentReceiver = currentReceiver;
    }

    public FormMode getFormMode() {
        return formMode;
    }

    public void setFormMode(FormMode formMode) {
        this.formMode = formMode;
    }

    public List<Receiver> getFilteredReceiver() {
        return filteredReceiver;
    }

    public void setFilteredReceiver(List<Receiver> filteredReceiver) {
        this.filteredReceiver = filteredReceiver;
    }

        /**
     * Creates a new instance of Receiver
     */
    public ReceiverBean() {
    }

    @PostConstruct
    public void initBean() {
        //defaul the birth date
        setBirthYear(2016);
        // Month index start from 0
        setBirthMonth(1);
        // Day index start from 1
        setBirthDay(1);
        // create a new Receiver entity instance
        currentReceiver = new Receiver();
        List<String> interistrings = new ArrayList<>();
        currentReceiver.setInterestings(interistrings);
        currentReceiver.setInterestings(new ArrayList<String>());
        // init ReceiverDAO
        receiverDAO = new receiverDAO();
        receiverDAO.setPath(FacesContext.getCurrentInstance().getExternalContext().getRealPath("/"));
        receiverDAO.setFilename(FILENAME);
    }

    public receiverDAO getReceiverDAO() {
        return receiverDAO;
    }

    public void setReceiverDAO(receiverDAO receiverDAO) {
        this.receiverDAO = receiverDAO;
    }

    public int getBirthYear() {
        return birthYear;
    }

    public void setBirthYear(int birthYear) {
        this.birthYear = birthYear;
    }

    public int getBirthMonth() {
        return birthMonth;
    }

    public void setBirthMonth(int birthMonth) {
        this.birthMonth = birthMonth;
    }

    public int getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(int birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * 儲存 {@link #receiverEntity} 到檔案中。
     */
    public void save() {
        // 你沒有此目標 facelets
//        String targetPage = "/manage/cases/listAllReceivers";
//        String targetPage = "/individual";
        // create the year, month, and day fields to date
        StringBuilder birthDateBuilder = new StringBuilder();
        birthDateBuilder.append(getBirthYear()).append("/");
        birthDateBuilder.append(getBirthMonth()).append("/");
        birthDateBuilder.append(getBirthDay());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date birthDate = Calendar.getInstance().getTime();
        try {
            birthDate = sdf.parse(birthDateBuilder.toString());
        } catch (ParseException ex) {
            Logger.getLogger(ReceiverBean.class.getName()).log(Level.SEVERE, null, ex);
            // Throw error Message
            FacesContext.getCurrentInstance().addMessage(null,
                    new FacesMessage("Errors occur when make the birth date."));
        }
        //Set the birth date property for the Receiver entity.
        currentReceiver.setBirth(birthDate);
        // call ReceiverDAO instance to save to file
        receiverDAO.save(currentReceiver);
        prepareAnotherCreate();
//        return targetPage;
    }

    /**
     * 為輸入下一筆新資料作準備動作。 先顯示對話框，表示儲存完成。之後，建立一個新的 {@link Receiver} 實體，供新的資料輸入。
     */
    private void prepareAnotherCreate() {
        // 顯示 MessageBox 訊息，表示儲存成功
        RequestContext.getCurrentInstance().showMessageInDialog(new FacesMessage("建檔成功"));
        currentReceiver = new Receiver();
    }

    /**
     * Get all receivers.
     *
     * @return
     */
    public List<Receiver> getReceivers() {
        List<Receiver> allList = null;
        allList = receiverDAO.getAll();
        return allList;
    }

    public List<Receiver> getAllIndividualData() {
        return receiverDataFacade.findAll();
    }

    /**
     * 建立新的 {@code Receiver} 實體，用以記錄使用者輸入的新資料。 Create a new {@code Receiver}
     * instance and assign to {@link ReceiverBean#receiverEntity}.
     *
     * @return 跳轉到輸入個案資料的頁面
     */
    public String prepareCreate() {
        //String targetPage = "individual-add";
        //receiverEntity = new Receiver();
        setBirthYear(1980);
        setBirthMonth(1);
        setBirthDay(1);
        //return targetPage;
        currentReceiver = new Receiver();
        formMode = FormMode.CREATE;
        return RECEIVER_ADD_PAGE;
    }

    public String saveIndividual() {
        
        try {
            currentReceiver.setBirth(convertBirthYearMonthDay());
        } catch (ParseException ex) {
            Logger.getLogger(ReceiverBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (formMode == FormMode.CREATE) {
            receiverDataFacade.create(currentReceiver);
        } else {
            receiverDataFacade.edit(currentReceiver);
        }
        return RECEIVER_DATA_PAGE;
    }

    public String prepareEdit(Receiver receiver) {
        currentReceiver = receiver;
        formMode = FormMode.EDIT;
        return RECEIVER_ADD_PAGE;
    }

    public void removeindividualData() {
        receiverDataFacade.remove(currentReceiver);
        currentReceiver = null;
    }

    public void removeIndividualAction(Receiver receiver) {
        currentReceiver = receiver;
        RequestContext requestContext = RequestContext.getCurrentInstance();
        requestContext.execute("PF('deleteDialogVar').show();");
    }

    public String viewIndividualAction(Receiver receiver) {
        currentReceiver = receiver;
        return RECEIVER_VIEWDETAIL_PAGE;
    }
    
    public Date convertBirthYearMonthDay() throws ParseException{
        StringBuilder birthDateStrBuffer = new StringBuilder();
        birthDateStrBuffer.append(Integer.toString(getBirthYear())).append("/");
        birthDateStrBuffer.append(Integer.toString(getBirthMonth())).append("/");
        birthDateStrBuffer.append(Integer.toString(getBirthDay()));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        
        return dateFormat.parse(birthDateStrBuffer.toString());
    }
}

src/java/manageBean/TicketDataBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manageBean;


import entity.Ticket;
import entity.TicketDataFacade;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import manageBean.TicketDataBean.FormMode;
import org.primefaces.context.RequestContext;

/**
 *
 * @author steven
 */
@Named(value = "ticketDataBean")
@SessionScoped
public class TicketDataBean implements Serializable {

    final static public String TICKET_ADD_PAGE = "ticketData-add";
    final static public String TICKET_DATA_PAGE = "ticketData";
    final static public String TICKET_VIEWDETAIL_PAGE = "ticketData-detail";


    enum FormMode {
        CREATE, EDIT, REMOVE
    }

    @EJB
    private TicketDataFacade ticketDataFacade;
    private Ticket currentTicketData;
    private FormMode formMode;

    public FormMode getFormMode() {
        return formMode;
    }

    public void setFormMode(FormMode formMode) {
        this.formMode = formMode;
    }

    public static Date getCurrentDate() {
        Calendar cal = Calendar.getInstance();
        return cal.getTime();
    }

    public TicketDataFacade getTicketDataFacade() {
        return ticketDataFacade;
    }

    public void setTicketDataFacade(TicketDataFacade ticketDataFacade) {
        this.ticketDataFacade = ticketDataFacade;
    }

    public Ticket getCurrentTicketData() {
        return currentTicketData;
    }

    public void setCurrentTicketData(Ticket currentTicketData) {
        this.currentTicketData = currentTicketData;
    }

    public List<Ticket> getAllTickerData() {
        return ticketDataFacade.findAll();
    }

    /**
     * 請直接使用 {@link #getCurrentDate() }
     *
     * @deprecated 2017/3/23 by hychen39@gmail.com
     * @return
     */
    public Date prepareCreateDate() {
        Calendar cal = Calendar.getInstance();
        return cal.getTime();
    }

    /**
     * Save the {@link #currentTicketData} to database by calling the
     * {@link #ticketDataFacade}.
     */
    public String saveTicket() {
        if (formMode == FormMode.CREATE) {
            ticketDataFacade.create(currentTicketData);
        } else {
            currentTicketData.setCreate_date(getCurrentDate());
            ticketDataFacade.edit(currentTicketData);
        }
        return TICKET_DATA_PAGE;
    }

    public String prepareCreate() {
        currentTicketData = new Ticket();
        currentTicketData.setCreate_date(getCurrentDate());
        formMode = FormMode.CREATE;
        return TICKET_ADD_PAGE;
    }

    public String prepareEdit(Ticket ticket) {
        currentTicketData = ticket;
        formMode = FormMode.EDIT;
        return TICKET_ADD_PAGE;
    }

    public void removeTicketData() {
        ticketDataFacade.remove(currentTicketData);
        currentTicketData = null;
    }

    public void removeTicketDataAction(Ticket ticket) {
        currentTicketData = ticket;
        RequestContext requestContext = RequestContext.getCurrentInstance();
        requestContext.execute("PF('deleteDialogVar').show();");
    }

    public String viewTicketDataAction(Ticket ticket) {
        currentTicketData = ticket;
        return TICKET_VIEWDETAIL_PAGE;
    }
    
    /**
     * Prepare for posting operation.
     * Call PrimeFace dialog <code>addNewPostDialogVar</code> to show up.
     * @param ticket Ticket to post.
     */
    public void preparePosting(Ticket ticket){
        currentTicketData = ticket;
        
        RequestContext.getCurrentInstance().execute("PF('addNewPostDialogVar').show();");
        
    }
    public void prepareOffPosting(Ticket ticket){
        currentTicketData = ticket;
        RequestContext.getCurrentInstance().execute("PF('delPostDialogVar').show();");
    }
    public boolean isOnShelf(Ticket ticket){
        return ticket.getStatus().equals(Ticket.Status.ON_SHELF);
    }
    
    public boolean isOffShelf(Ticket ticket){
        return ticket.getStatus().equals(Ticket.Status.OFF_SHELF);
    }
}

web/category.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <link rel="stylesheet" type="text/css" href="css/style.css"/>
    <link rel="stylesheet" type="text/css" href="css/category.css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <h:head>
        <title>票券媒合系統</title>
        <h:outputStylesheet library="css" name="category.css" />
        <h:outputStylesheet library="css" name="style.css" />
        <script src="https://use.fontawesome.com/2a877f719f.js"></script>
    </h:head>
    <h:body>
        <h1 class="order-table-title">票券分類一覽表</h1>
        <h:form>
            <h:dataTable value="#{ticketCategoryBean.allCategories}" var="c"
                         styleClass="order-table" 
                         headerClass="order-table-header"
                         rowClasses="order-table-odd-row, order-table-even-row"
                         columnClasses="order-table-name-column,order-table-icon-colume">
                <h:column>
                    <f:facet name="header" > 類別名稱 </f:facet>          
                    <h:outputText value="#{c.name}"/>
                </h:column>
                <h:column>
                    <!--呼叫 managed bean method 記錄修改前的值-->
                    <!--ToDo: edit Action-->
                    <!--editCateogyr() will pop up a dialog for editing.-->
                    <p:commandButton  action="#{ticketCategoryBean.updateCategoryAction(c)}" value="修改" icon="fa fa-pencil" />
                    <!--ToDo: delete action-->
                    <p:commandButton  action="#{ticketCategoryBean.removeCategoryAction(c)}" value="刪除" icon="fa fa-trash" />
                </h:column>
            </h:dataTable><br/><br/>
            <div id="button">
                <p:row>
                    <p:commandButton styleClass="order-table-button" 
                                     value="新增票券分類" 
                                     actionListener="#{ticketCategoryBean.addCategoryAction}"
                                     onclick="PF('addDialogVar').show();" />
                    <p:commandButton value="返回主畫面" action="index" />
                </p:row>
            </div>
        </h:form>

        <div id="category">
            <p:dialog id="addDialogID"
                      header="新增票券類別"
                      widgetVar="addDialogVar"
                      modal="true" >
                <h:outputText value="請輸入欲新增之類別名稱: " />
                <h:form>
                    <h:inputText value="#{ticketCategoryBean.currentCategory.name}"/><br/>
                    <h:commandButton styleClass="add-ind-button" value="取消" onclick="PF('addDialogVar').hide();" actionListener="#{ticketCategoryBean.CategoryCancel}" />
                    <h:commandButton styleClass="add-ind-button" value="送出" action="#{ticketCategoryBean.addCategoryDB}" />
                </h:form>
            </p:dialog>
            <!--使用 lazy loading 功能，讓對話框顯示是採取讀取 managed bean 的 property 值-->
            <!-- modal="true"  是表示綁定對話框只能操作對話框 不能執行對話框以外的動作-->
            <p:dialog id="editDialogID" header="修改票券類別" 
                      widgetVar="editDialogVar" 
                      modal="true" 
                      height="120"
                      dynamic="true">
                <h:outputText value="請輸入欲修改之類別名稱: " />
                <h:form>
                    <h:inputText value="#{ticketCategoryBean.currentCategory.name}" /><br/>
                    <h:commandButton styleClass="add-ind-button"  value="取消" onclick="PF('editDialogVar').hide();" actionListener="#{ticketCategoryBean.CategoryCancel}"/>
                    <h:commandButton styleClass="add-ind-button"  value="送出" action="#{ticketCategoryBean.updateCategoryDB}" />
                </h:form>
            </p:dialog>
            <p:dialog id="deleteDialogID" header="刪除票券類別" widgetVar="deleteDialogVar" modal="true" 
                      height="120" dynamic="true" closable="false" draggable="false" closeOnEscape="true" resizable="false">
                <h:form>
                    <h:outputText value="確認是否刪除 #{ticketCategoryBean.currentCategory.name} ? " /><br/><br/>
                    <h:commandButton styleClass="add-ind-button" value="取消" onclick="PF('deleteDialogVar').hide();" actionListener="#{ticketCategoryBean.CategoryCancel}"/>
                    <h:commandButton styleClass="add-ind-button" value="確定刪除" action="#{ticketCategoryBean.removeCategoryDB}" />
                </h:form>
            </p:dialog>
        </div>
    </h:body>
</html>

web/donerData-add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ps="http://xmlns.jcp.org/jsf/passthrough" >

    <h:head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>新增捐贈者-輸入表單</title>
        <h:outputStylesheet library="css" name="style.css" />
        <h:outputStylesheet library="css" name="donerdata.css" />
        <script src="https://use.fontawesome.com/2a877f719f.js"></script>
    </h:head>
    <h:body>
        <h:form id="donerdata"
                styleClass="table">
            <p:focus context="donerdata" />
            <p:messages  autoUpdate="true"/>
            <p:panelGrid style="width:100% ; height:100%;">
                <p:row>
                    <p:column class="add-ind-title" colspan="12">捐贈者資料</p:column>
                </p:row>
                <p:row>
                    <p:column colspan="2">建檔日期：</p:column>
                    <p:column colspan="6">
                        <p:outputLabel id="create_date" value="#{donorDataBean.prepareCreateDate()}" >
                            <f:convertDateTime timeZone="Asia/Taipei" type="both" />
                        </p:outputLabel>
                    </p:column>
                </p:row>                
                <p:row>
                    <p:column colspan="2">類別：</p:column>
                    <p:column colspan="6" >
                        <p:selectOneMenu 
                            id="type" 
                            value="#{donorDataBean.currentDonerData.category}" 
                            converter="donerCategoryConverter">
                            <f:selectItem itemLabel="請選擇" itemValue="0" />
                            <f:selectItems  
                                value="#{donerCategoryBean.allCategories}" 
                                var="doner" itemLabel="#{doner.name}"
                                itemValue="#{doner}"/>
                        </p:selectOneMenu>
                    </p:column>
                </p:row>                
                <p:row>
                    <p:column colspan="2">捐贈者名稱：</p:column>
                    <p:column colspan="6">
                        <p:inputText id="donername" 
                                     value="#{donorDataBean.currentDonerData.donername}"
                                     maxlength="50" 
                                     required="true"
                                     requiredMessage="必要欄位"
                                     ps:placeholder="字數50字以內">
                            <f:validateLength minimum="1" maximum="50" />
                            <p:ajax process="@this" update="donernameError" />
                        </p:inputText>
                        <p:message id="donernameError" for="donername" />
                    </p:column>
                </p:row>                
                <p:row>
                    <p:column colspan="2">聯絡人：</p:column>
                    <p:column colspan="6">
                        <p:inputText maxlength="50" ps:placeholder="字數50字以內" value="#{donorDataBean.currentDonerData.connectname}"/>
                    </p:column>
                </p:row>                
                <p:row>
                    <p:column colspan="2">電話：</p:column>
                    <p:column colspan="6">
                        <p:inputText style="width:3% " value="#{donorDataBean.currentDonerData.area_code}" />－
                        <p:inputText value="#{donorDataBean.currentDonerData.tel}" /> 例如：04-12345678 or 09-12345678
                    </p:column>
                </p:row>                
                <p:row>
                    <p:column colspan="2">地址：</p:column>
                    <p:column colspan="2">
                        <p:inputText maxlength="50" ps:placeholder="字數50字以內(可略)" value="#{donorDataBean.currentDonerData.address}"/>
                    </p:column>
                </p:row>                
                <p:row>
                    <p:column colspan="2">簡介</p:column>
                    <p:column colspan="7">
                        <p:inputTextarea style="width: 28% " maxlength="200" ps:placeholder="字數200字以內(可略)" value="#{donorDataBean.currentDonerData.content}"/>
                    </p:column>
                </p:row>                
            </p:panelGrid>
            <p:commandButton styleClass="add-ind-button" value="取消" immediate="true" action="donerData" />
            <p:commandButton styleClass="add-ind-button" value="送出" action="donerData-view"/>
        </h:form>           
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <title>票券媒合系統</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <h:outputStylesheet library="css" name="style.css" />
        <!--<script src="https://use.fontawesome.com/2a877f719f.js"></script>-->
    </h:head>
    <h:body>
        <div id="index">
            <h1>主畫面</h1>
            <h:form>
                <p:commandButton styleClass="order-table" value="個人資料" action="individual" />
                <p:commandButton styleClass="order-table" value="票券類別一覽表" action="category" />
                <p:commandButton styleClass="order-table" value="票券資料一覽表" action="ticketData" />
                <p:commandButton styleClass="order-table" value="捐贈者資料一覽表" action="donerData" />
            </h:form>
        </div>
    </h:body>
</html>